baseURL = "https://lassebenni.github.io/"
languageCode = "en-us"
title = "Lasse on Data"
theme = "PaperMod"

[pagination]
  pagerSize = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
	subtitle = "data engineering, analytics engineering, automation and devops notes."
	# papermod params
	homeInfoParams = { Title = "Lasse on Data", Content = "data engineering, analytics engineering, automation and devops notes." }
	ShowReadingTime = true
	ShowShareButtons = true
	ShowSummary = true
	defaultTheme = "auto"
	disableSpecial1stPost = false
	
	# Table of Contents settings
	ShowToc = true
	TocOpen = true
	
	# Comments settings using giscus
	comments = true
	
[params.giscus]
	repo = "lassebenni/lassebenni.github.io"
	repoId = "MDEwOlJlcG9zaXRvcnkzNjU2MzYzOA=="
	category = "General"
	categoryId = "MDE4OkRpc2N1c3Npb25DYXRlZ29yeTMyMjY4ODI3"
	mapping = "pathname"
	strict = "0"
	reactionsEnabled = "1"
	emitMetadata = "0"
	inputPosition = "bottom"
	theme = "preferred_color_scheme"
	lang = "en"
	# which sections to show on homepage and posts list
	mainSections = ["posts"]

	# newsletter settings (buttondown recommended)
	NewsletterSignup = "https://buttondown.email/lassebenni"

[params.newsletter]
  provider = "buttondown"
  handle = "lassebenni"

	# Optional 64x64 avatar image.
	avatar = "https://pbs.twimg.com/profile_images/1265659616056283136/ei4hG_1n_400x400.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	customCSS = ["css/custom.css", "css/toc-sidebar.css"]  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

	# remove leftover tinyletter
	# NewsletterSignup = "https://tinyletter.com/lbenninga"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/lassebenni/"

[[params.social]]
name = "rss"
icon = "rss"
url = "index.xml"




[taxonomies]
   tag = "tags"
